name: Build IPA on Push to Master

on:
  push:
    branches:
      - master
      - main

jobs:
  build-and-upload:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.8'

    - name : Pod install
      run: |
          cd provider_shopper/ios/
          pwd
          ls
          flutter clean 
          flutter pub get
          rm -rf Podfile.lock
          pod repo update
          pod update FirebaseSessions
          pod install
    

    - name: Build iOS App
      run: |
        cd provider_shopper/ios/
        flutter build ios --release --no-codesign 

    - name: Build IPA
      run: |
        cd provider_shopper/ios/
        xcodebuild -workspace ios/Runner.xcworkspace \
                   -scheme Runner \
                   -configuration Release \
                   -archivePath $PWD/build/Runner.xcarchive \
                   archive \
                   -quiet || exit

        xcodebuild -exportArchive \
                   -archivePath $PWD/build/Runner.xcarchive \
                   -exportOptionsPlist ExportOptions.plist \
                   -exportPath $PWD/build/Runner.ipa \
                   -quiet || exit

    - name: Upload IPA artifact
      uses: actions/upload-artifact@v2
      with:
        name: MyApp-IPA
        path: ./build/Runner.ipa
